[package]
name = "lock-analyzer"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
ron.workspace = true

[dependencies.serde]
workspace = true
features = ["default", "serde_derive"]

[lints.clippy]
disallowed_types = "allow"
