[package]
name = "wgpu-hello-workgroups-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu hello workgroups example"
publish = false

[[bin]]
name = "hello-workgroups"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
futures-intrusive.workspace = true
log.workspace = true
pollster.workspace = true
wgpu.workspace = true
wgpu-example.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Document"] }
