// Compiled with:
// glslang -V -o naga/tests/in/spv/spec-constant-op.spv naga/tests/in/spv/spec-constant-op.comp
// Disassembled with:
// spirv-dis naga/tests/in/spv/spec-constant-op.spv -o naga/tests/in/spv/spec-constant-op.spvasm
// Based on this test of glslang: https://github.com/KhronosGroup/glslang/blob/main/Test/spv.specConstantOperations.vert
#version 450

layout(constant_id = 0) const float sp_float = 3.1415926;
layout(constant_id = 1) const int sp_int = 10;
layout(constant_id = 2) const uint sp_uint = 100;
layout(constant_id = 3) const int sp_sint = -10;

//
// Scalars
//

// uint/int <-> bool conversion
const bool bool_from_int = bool(sp_int);             // bool(3) = true
const bool bool_from_uint = bool(sp_uint);           // bool(20) = true
const int int_from_bool = int(bool_from_int);        // int(true) = 1
const uint uint_from_bool = uint(bool_from_int);     // uint(true) = 1

// Negate and Not
const int negate_int = -sp_int;                      // -3 = -3
const int not_int = ~sp_int;                         // ~3 = -4

// Add and Subtract
const int sp_int_add_two = sp_int + 2;                          // 3 + 2 = 5
const int sp_int_add_two_sub_three = sp_int + 2 - 3;            // 3 + 2 - 3 = 2
const int sp_int_add_two_sub_four = sp_int_add_two - 4;         // 5 - 4 = 1

// Mul, Div
const int sp_sint_mul_two = sp_sint * 2;                        // 4 * 2 = 8
const uint sp_uint_mul_two = sp_uint * 2;                       // 20 * 2 = 40
const int sp_sint_mul_two_div_five = sp_sint_mul_two / 5;       // 8 / 5 = 1
const uint sp_uint_mul_two_div_five = sp_uint_mul_two / 5;      // 40 / 5 = 8
const int sp_sint_mul_three_div_five = sp_sint * 3 / 5;         // 4 * 3 / 5 = 2

// Rem
const int sp_sint_rem_four = sp_sint % 4;                       // 4 % 4 = 0
const uint sp_uint_rem_four = sp_uint % 4;                      // 20 % 4 = 0

// Shift (the shift value must be an unsigned integer)
const int sp_sint_shift_right_arithmetic = sp_sint >> 10u;      // 4 >> 10 = 0
const uint sp_uint_shift_right_arithmetic = sp_uint >> 20u;     // 20 >> 20 = 0
const int sp_sint_shift_left = sp_sint << 1u;                   // 4 << 1 = 8
const uint sp_uint_shift_left = sp_uint << 2u;                  // 20 << 2 = 80

// Bitwise And, Or, Xor
const int sp_sint_and_3 = sp_sint & 3;                          // 4 & 3 = 0
const int sp_sint_or_256 = sp_sint | 0x100;                     // 4 | 256 = 260
const uint sp_uint_xor_512 = sp_uint ^ 0x200;                   // 20 ^ 512 = 532

// Scalar comparison
const bool sp_int_lt_sp_sint = sp_int < sp_sint;                // 3 < 4 = true
const bool sp_int_le_sp_sint = sp_int <= sp_sint;               // 3 <= 4 = true
const bool sp_uint_equal_sp_uint = sp_uint == sp_uint;          // 20 == 20 = true
const bool sp_uint_not_equal_sp_uint = sp_uint != sp_uint;      // 20 != 20 = false
const bool sp_int_gt_sp_sint = sp_int > sp_sint;                // 3 > 4 = false
const bool sp_int_ge_sp_sint = sp_int >= sp_sint;               // 3 >= 4 = false

// Logical operations
const bool logical_and = bool_from_int && bool_from_uint;       // true && true = true
const bool logical_or = bool_from_int || bool_from_uint;        // true || true = true
const bool logical_equal = bool_from_int == bool_from_uint;     // true == true = true
const bool logical_not_equal = bool_from_int != bool_from_uint; // true != true = false

// ternary
layout(constant_id = 4) const int a = 4;
layout(constant_id = 5) const int b = 6;
layout(constant_id = 6) const bool c = true;
const int t1 = c ? 13 : 17;             // true ? 13 : 17 = 13
const int t2 = c ? a : 17;              // true ? 1 : 17 = 1
const int t3 = true ? a : 17;           // true ? 1 : 17 = 1
const int t4 = a > b ? 13 + a : 17 * b; // 1 > 0 ? 13+1 : 17*0 = 14

layout(set = 0, binding = 0) buffer OutputBuffer {
    uint bool_from_int_val;
    uint bool_from_uint_val;
    int int_from_bool_val;
    uint uint_from_bool_val;
    int negate_int_val;
    int not_int_val;
    int sp_int_add_two_val;
    int sp_int_add_two_sub_three_val;
    int sp_int_add_two_sub_four_val;
    int sp_sint_mul_two_val;
    uint sp_uint_mul_two_val;
    int sp_sint_mul_two_div_five_val;
    uint sp_uint_mul_two_div_five_val;
    int sp_sint_mul_three_div_five_val;
    int sp_sint_rem_four_val;
    uint sp_uint_rem_four_val;
    int sp_sint_shift_right_arithmetic_val;
    uint sp_uint_shift_right_arithmetic_val;
    int sp_sint_shift_left_val;
    uint sp_uint_shift_left_val;
    int sp_sint_and_3_val;
    int sp_sint_or_256_val;
    uint sp_uint_xor_512_val;
    uint sp_int_lt_sp_sint_val;
    uint sp_int_le_sp_sint_val;
    uint sp_uint_equal_sp_uint_val;
    uint sp_uint_not_equal_sp_uint_val;
    uint sp_int_gt_sp_sint_val;
    uint sp_int_ge_sp_sint_val;
    uint logical_and_val;
    uint logical_or_val;
    uint logical_equal_val;
    uint logical_not_equal_val;
    int t1_val;
    int t2_val;
    int t3_val;
    int t4_val;
} output_buffer;

void main() {
    output_buffer.bool_from_int_val = uint(bool_from_int);
    output_buffer.bool_from_uint_val = uint(bool_from_uint);
    output_buffer.int_from_bool_val = int_from_bool;
    output_buffer.uint_from_bool_val = uint_from_bool;
    output_buffer.negate_int_val = negate_int;
    output_buffer.not_int_val = not_int;
    output_buffer.sp_int_add_two_val = sp_int_add_two;
    output_buffer.sp_int_add_two_sub_three_val = sp_int_add_two_sub_three;
    output_buffer.sp_int_add_two_sub_four_val = sp_int_add_two_sub_four;
    output_buffer.sp_sint_mul_two_val = sp_sint_mul_two;
    output_buffer.sp_uint_mul_two_val = sp_uint_mul_two;
    output_buffer.sp_sint_mul_two_div_five_val = sp_sint_mul_two_div_five;
    output_buffer.sp_uint_mul_two_div_five_val = sp_uint_mul_two_div_five;
    output_buffer.sp_sint_mul_three_div_five_val = sp_sint_mul_three_div_five;
    output_buffer.sp_sint_rem_four_val = sp_sint_rem_four;
    output_buffer.sp_uint_rem_four_val = sp_uint_rem_four;
    output_buffer.sp_sint_shift_right_arithmetic_val = sp_sint_shift_right_arithmetic;
    output_buffer.sp_uint_shift_right_arithmetic_val = sp_uint_shift_right_arithmetic;
    output_buffer.sp_sint_shift_left_val = sp_sint_shift_left;
    output_buffer.sp_uint_shift_left_val = sp_uint_shift_left;
    output_buffer.sp_sint_and_3_val = sp_sint_and_3;
    output_buffer.sp_sint_or_256_val = sp_sint_or_256;
    output_buffer.sp_uint_xor_512_val = sp_uint_xor_512;
    output_buffer.sp_int_lt_sp_sint_val = uint(sp_int_lt_sp_sint);
    output_buffer.sp_int_le_sp_sint_val = uint(sp_int_le_sp_sint);
    output_buffer.sp_uint_equal_sp_uint_val = uint(sp_uint_equal_sp_uint);
    output_buffer.sp_uint_not_equal_sp_uint_val = uint(sp_uint_not_equal_sp_uint);
    output_buffer.sp_int_gt_sp_sint_val = uint(sp_int_gt_sp_sint);
    output_buffer.sp_int_ge_sp_sint_val = uint(sp_int_ge_sp_sint);
    output_buffer.logical_and_val = uint(logical_and);
    output_buffer.logical_or_val = uint(logical_or);
    output_buffer.logical_equal_val = uint(logical_equal);
    output_buffer.logical_not_equal_val = uint(logical_not_equal);
    output_buffer.t1_val = t1;
    output_buffer.t2_val = t2;
    output_buffer.t3_val = t3;
    output_buffer.t4_val = t4;
}
