[package]
name = "naga-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Common types for naga and wgpu"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
arbitrary = { workspace = true, features = ["derive"], optional = true }
hashbrown.workspace = true
indexmap.workspace = true
rustc-hash.workspace = true
serde = { workspace = true, features = ["alloc", "derive"], optional = true }
thiserror.workspace = true

[features]
arbitrary = ["dep:arbitrary", "indexmap/arbitrary", "std"]
deserialize = ["dep:serde", "indexmap/serde"]
serialize = ["dep:serde", "indexmap/serde"]
std = []

[lints]
workspace = true
