[package]
name = "wgpu-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Common types and utilities for wgpu, the cross-platform, safe, pure-rust graphics API"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

# Override the workspace's `rust-version` key. `wgpu-core` and its dependencies
# have a less strict MSRV, to allow firefox more leeway in updating their Rust toolchain.
#
# See the repo README for more information on MSRV policy.
rust-version = "1.87"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]

[lib]

[dependencies]
naga-types = { workspace = true, features = [] }

bitflags.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
exhaust = { workspace = true, optional = true }
log.workspace = true
raw-window-handle.workspace = true
serde = { workspace = true, default-features = false, features = [
    "alloc",
    "derive",
], optional = true }
static_assertions.workspace = true

[dev-dependencies]
exhaust.workspace = true
hashbrown.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true, default-features = false, optional = true }
web-sys = { workspace = true, default-features = false, features = [
    "HtmlCanvasElement",
    "HtmlImageElement",
    "HtmlVideoElement",
    "ImageBitmap",
    "ImageData",
    "OffscreenCanvas",
    "VideoFrame",
], optional = true }

[features]
default = ["std"]
# Enables some internal instrumentation for debugging purposes.
counters = []
exhaust = ["dep:exhaust"]
fragile-send-sync-non-atomic-wasm = []
serde = [
    "bitflags/serde",
    "dep:serde",
    "naga-types/deserialize",
    "naga-types/serialize",
]
std = ["js-sys?/std", "naga-types/std", "web-sys?/std"]
strict_asserts = []
# Enables variants of `Trace` other than `Trace::Off`
trace = ["serde/std", "std"]
# Enable web-specific dependencies for wasm.
web = ["dep:js-sys", "dep:web-sys"]

[lints.clippy]
alloc_instead_of_core = "warn"
std_instead_of_alloc = "warn"
std_instead_of_core = "warn"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(web_sys_unstable_apis)"] }
