[package]
name = "wgpu-core-platform-apple"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Feature unification helper crate for Apple platforms"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
metal = ["wgpu-hal/metal"]
angle = ["wgpu-hal/gles"]
vulkan-portability = ["wgpu-hal/vulkan"]

[target.'cfg(target_vendor = "apple")'.dependencies]
wgpu-hal.workspace = true
