[package]
name = "naga-test"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "common code for naga tests"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = false

[dependencies]
bitflags.workspace = true
naga = { workspace = true, features = [
    "deserialize",
    "dot-out",
    "fs",
    "glsl-in",
    "glsl-out",
    "hlsl-out",
    "msl-out",
    "serialize",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
spirv = { workspace = true, features = ["deserialize"] }
toml.workspace = true

[features]
