[bans]
multiple-versions = "deny"
skip-tree = [
    { name = "windows-sys", version = "0.45" },
    { name = "winit", version = "0.29" },
    { name = "rustc-hash", version = "1.1.0" },

    # introduced by Deno, to be investigated
    { name = "petgraph", version = "0.6.5" },

    # Winit 0.30 uses an older objc2
    { name = "objc2-foundation", version = "0.2" },
]
skip = [
    # Deno uses an old version
    { name = "bincode", version = "1.3.3" },
    { name = "which", version = "6.0.3" },

    # Winit uses an old version
    { name = "windows-sys", version = "0.52.0" },

    # parking-lot uses an old version
    { name = "redox_syscall", version = "0.5.18" },
]
wildcards = "deny"
allow-wildcard-paths = true

[advisories]
ignore = [
    # `paste` crate is no longer maintained https://rustsec.org/advisories/RUSTSEC-2024-0436
    # It's a dependency of `metal` (which is to be replaced with `objc2-metal`), and a
    # transitive dependency of `deno`. https://github.com/gfx-rs/wgpu/issues/7873
    "RUSTSEC-2024-0436",
    # `unic-*` crates are no longer maintained https://rustsec.org/advisories/RUSTSEC-2025-0100
    # These are used via `deno`. https://github.com/gfx-rs/wgpu/issues/8393
    "RUSTSEC-2025-0075",
    "RUSTSEC-2025-0080",
    "RUSTSEC-2025-0081",
    "RUSTSEC-2025-0098",
    "RUSTSEC-2025-0100",
    # `bincode` is no longer maintained https://rustsec.org/advisories/RUSTSEC-2025-0141
    # We only use it directly for tests and tools. It is also used indirectly via deno.
    "RUSTSEC-2025-0141",
]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Zlib",
]
private = { ignore = true }

[sources]
allow-git = [
    # Waiting on releases; used in examples/tests only

    # Pending a release for https://github.com/Xudong-Huang/generator-rs/pull/75
    "https://github.com/Xudong-Huang/generator-rs",
    # Pending a release for https://github.com/gfx-rs/rspirv
    "https://github.com/gfx-rs/rspirv",
]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"

[sources.allow-org]
github = []
