[workspace]
resolver = "2"
members = [
    "cts_runner",
    "deno_webgpu",

    # default members
    "benches",
    "examples/bug-repro/*",
    "examples/features",
    "examples/standalone/*",
    "lock-analyzer",
    "naga",
    "naga-cli",
    "naga-test",
    "naga-types",
    "naga/fuzz",
    "naga/hlsl-snapshots",
    "naga/xtask",
    "player",
    "tests",
    "wgpu",
    "wgpu-core",
    "wgpu-core/platform-deps/*",
    "wgpu-hal",
    "wgpu-info",
    "wgpu-macros",
    "wgpu-naga-bridge",
    "wgpu-types",
    "xtask",
]
exclude = []
default-members = [
    "benches",
    "examples/bug-repro/*",
    "examples/features",
    "examples/standalone/*",
    "lock-analyzer",
    "naga",
    "naga-cli",
    "naga-test",
    "naga-types",
    "naga/fuzz",
    "naga/hlsl-snapshots",
    "naga/xtask",
    "player",
    "tests",
    "wgpu",
    "wgpu-core",
    "wgpu-core/platform-deps/*",
    "wgpu-hal",
    "wgpu-info",
    "wgpu-macros",
    "wgpu-naga-bridge",
    "wgpu-types",
    "xtask",
]

[workspace.package]
version = "29.0.0"
authors = ["gfx-rs developers"]
edition = "2021"
rust-version = "1.93"
homepage = "https://wgpu.rs/"
repository = "https://github.com/gfx-rs/wgpu"
license = "MIT OR Apache-2.0"
keywords = ["graphics"]

[workspace.dependencies]
naga = { path = "./naga", version = "29.0.0" }
naga-test = { path = "./naga-test" }
naga-types = { path = "./naga-types", version = "29.0.0" }
wgpu = { path = "./wgpu", version = "29.0.0", default-features = false, features = [
    "angle",
    "dx12",
    "gles",
    "metal",
    "serde",
    "static-dxc",
    "std",
    "vulkan",
    "vulkan-portability",
    "wgsl",
] }
wgpu-core = { path = "./wgpu-core", version = "29.0.0" }
wgpu-hal = { path = "./wgpu-hal", version = "29.0.0" }
wgpu-macros = { path = "./wgpu-macros", version = "29.0.0" }
wgpu-naga-bridge = { path = "./wgpu-naga-bridge", version = "29.0.0" }
wgpu-test = { path = "./tests", version = "29.0.0" }
wgpu-types = { path = "./wgpu-types", version = "29.0.0", default-features = false }

# These _cannot_ have a version specified. If it does, crates.io will look
# for a version of the package on crates when we publish naga. Path dependencies
# are allowed through though.
hlsl-snapshots = { path = "naga/hlsl-snapshots" }

wgpu-core-deps-apple = { path = "./wgpu-core/platform-deps/apple", version = "29.0.0" }
wgpu-core-deps-emscripten = { path = "./wgpu-core/platform-deps/emscripten", version = "29.0.0" }
wgpu-core-deps-wasm = { path = "./wgpu-core/platform-deps/wasm", version = "29.0.0" }
wgpu-core-deps-windows-linux-android = { path = "./wgpu-core/platform-deps/windows-linux-android", version = "29.0.0" }

anyhow = { version = "1.0.87", default-features = false }
approx = "0.5"
arbitrary = "1.4.2"
argh = "0.1.13"
arrayvec = { version = "0.7.1", default-features = false }
bincode = "2"
bit-set = { version = "0.10", default-features = false }
bit-vec = { version = "0.9.1", default-features = false }
bitflags = "2.9"
bytemuck = { version = "1.22", features = [
    "extern_crate_alloc",
    "min_const_generics",
] }
cargo_metadata = "0.23"
cfg_aliases = "0.2.1"
cfg-if = "1"
codespan-reporting = { version = "0.13", default-features = false }
diff = "0.1"
document-features = "0.2.10"
encase = "0.12"
env_logger = { version = "0.11", default-features = false }
exhaust = "0.2"
fern = "0.7"
flume = "0.12"
futures-lite = "2"
glam = "0.33.0"
glob = "0.3"
half = { version = "2.5", default-features = false }  # We require 2.5 to have `Arbitrary` support.
hashbrown = { version = "0.17", default-features = false, features = [
    "default-hasher",
    "inline-more",
] }
heck = "0.5"
image = { version = "0.25", default-features = false, features = ["png"] }
indexmap = { version = "2.11.4", default-features = false }
indicatif = "0.18"
itertools = { version = "0.14" }
jobserver = "0.1"
ktx2 = "0.5"
libc = { version = "0.2.172", default-features = false }
# See https://github.com/rust-fuzz/libfuzzer/issues/126
libfuzzer-sys = ">0.4.0,<=0.4.7"
libloading = "0.8"
libm = { version = "0.2.6", default-features = false }
libtest-mimic = "0.8"
log = "0.4.29"
macro_rules_attribute = "0.2"
nanorand = { version = "0.8", default-features = false, features = ["wyrand"] }
nanoserde = "0.2"
noise = "0.9"
num_cpus = "1"
# `half` requires 0.2.16 for `FromBytes` and `ToBytes`.
num-traits = { version = "0.2.16", default-features = false }
nv-flip = "0.1"
obj = "0.10"
# NOTE: once_cell/std is *required* for some commonly-used features, selecting this per crate
once_cell = { version = "1.21", default-features = false }
# Firefox has 3.4.0 vendored, so we allow that version in our dependencies
ordered-float = { version = ">=3, <6.0", default-features = false }
parking_lot = "0.12.3"
petgraph = { version = "0.8", default-features = false }
pico-args = { version = "0.5", features = [
    "combined-flags",
    "eq-separator",
    "short-space-opt",
] }
png = "0.18"
pollster = "0.4"
portable-atomic = "1.10"
portable-atomic-util = "0.2.4"
pp-rs = "0.2.1"
profiling = { version = "1.0.1", default-features = false }
quote = "1.0.38"
raw-window-handle = { version = "0.6.2", default-features = false }
rayon = "1.3"
regex-lite = "0.1"
renderdoc-sys = "1"
ron = "0.12"
rspirv = "0.13"
# NOTE: rustc-hash v2 is a completely different hasher with different performance characteristics
# see discussion here (including with some other alternatives): https://github.com/gfx-rs/wgpu/issues/6999
# (using default-features = false to support no-std build, avoiding any extra features that may require std::collections)
rustc-hash = { version = "1.1", default-features = false }
serde = { version = "1.0.225", default-features = false }
serde_json = "1.0.143"
shell-words = "1"
smallvec = "1.14"
spirv = "0.4"
static_assertions = "1.1"
strum = { version = "0.28", default-features = false, features = ["derive"] }
syn = "2.0.98"
tempfile = "3"
thiserror = { version = "2.0.12", default-features = false }
toml = "1.0.0"
tracy-client = "0.18"
trybuild = "1"
unicode-ident = "1.0.5"
walkdir = "2.3"
which = "8"
winit = { version = "0.30.8", features = ["android-native-activity"] }
xshell = "0.2.2"

# Metal dependencies
block2 = "0.6.2"
objc2 = "0.6.3"
objc2-core-foundation = { version = "0.3.2", default-features = false, features = [
    "CFCGTypes",
    "std",
] }
objc2-foundation = { version = "0.3.2", default-features = false, features = [
    "NSError",
    "NSProcessInfo",
    "NSRange",
    "NSString",
    "std",
] }
objc2-metal = { version = "0.3.2", default-features = false, features = [
    "MTLAccelerationStructure",
    "MTLAccelerationStructureCommandEncoder",
    "MTLAccelerationStructureTypes",
    "MTLAllocation",
    "MTLBlitCommandEncoder",
    "MTLBlitPass",
    "MTLBuffer",
    "MTLCaptureManager",
    "MTLCaptureScope",
    "MTLCommandBuffer",
    "MTLCommandEncoder",
    "MTLCommandQueue",
    "MTLComputeCommandEncoder",
    "MTLComputePass",
    "MTLComputePipeline",
    "MTLCounters",
    "MTLDepthStencil",
    "MTLDevice",
    "MTLDrawable",
    "MTLEvent",
    "MTLLibrary",
    "MTLPipeline",
    "MTLPixelFormat",
    "MTLRenderCommandEncoder",
    "MTLRenderPass",
    "MTLRenderPipeline",
    "MTLResidencySet",
    "MTLResource",
    "MTLSampler",
    "MTLStageInputOutputDescriptor",
    "MTLTexture",
    "MTLTypes",
    "MTLVertexDescriptor",
    "block2",
    "std",
] }
objc2-quartz-core = { version = "0.3.2", default-features = false, features = [
    "CALayer",
    "CAMetalLayer",
    "objc2-core-foundation",
    "objc2-metal",
    "std",
] }
raw-window-metal = "1.0"

# Vulkan dependencies
android_system_properties = "0.1.1"
ash = "0.38"

mach-dxcompiler-rs = { version = "0.1.4", default-features = false }  # remember to increase max_shader_model if applicable
# DX12 dependencies
range-alloc = "0.1"
windows-core = { version = "0.62", default-features = false }
windows-result = { version = "0.4", default-features = false }

# DX12 and Vulkan dependencies
gpu-allocator = { version = "0.28", default-features = false, features = [
    "hashbrown",
] }

glow = "0.17"
glutin = { version = "0.32", default-features = false }
glutin_wgl_sys = "0.6"
glutin-winit = { version = "0.5", default-features = false }
# Gles dependencies
khronos-egl = "6"

# DX12 and GLES dependencies
windows = { version = "0.62", default-features = false }

# wasm32 dependencies
console_error_panic_hook = "0.1.5"
console_log = "1"
js-sys = { version = "0.3.85", default-features = false }
wasm-bindgen = { version = "0.2.108", default-features = false }
wasm-bindgen-futures = { version = "0.4.58", default-features = false }
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3.85", default-features = false }
web-time = "1.1.0"

# deno dependencies
deno_console = "0.214.0"
deno_core = "0.355.0"
deno_error = "0.7.0"
deno_features = "0.11.0"
deno_unsync = "0.4.4"
deno_url = "0.214.0"
deno_web = "0.245.0"
deno_webgpu = { path = "./deno_webgpu", version = "0.181.0" }
deno_webidl = "0.214.0"
termcolor = "1.4.1"
tokio = "1.47"

# android dependencies
ndk-sys = "0.6"

[workspace.lints.clippy]
ref_as_ptr = "warn"
# NOTE: clippy configuration values (disallowed-types and
# large-error-threshold) are in other file: clippy.toml

# These overrides allow our examples to explicitly depend on release crates
[patch.crates-io]
wgpu = { path = "./wgpu" }

env_logger = { git = "https://github.com/rust-cli/env_logger.git", rev = "d550741", version = "0.11" }
libtest-mimic = { git = "https://github.com/cwfitzgerald/libtest-mimic.git", rev = "9979b3c", version = "0.8" }

# Speed up image comparison even in debug builds
[profile.dev.package."nv-flip-sys"]
opt-level = 3

[profile.release]
debug = true
lto = "thin"
