[files]
extend-exclude = [
    # spirv-asm isn't real source code
    '*.spvasm',
    'etc/big-picture.xml',
]

# Corrections take the form of a key/value pair. The key is the incorrect word
# and the value is the correct word. If the key and value are the same, the
# word is treated as always correct. If the value is an empty string, the word
# is treated as always incorrect.

[default.extend-words]
# Things that aren't typos
lod = "lod"
inout = "inout"
derivate = "derivate"
implace = "implace"
Ded = "Ded"           # This shows up in "ANDed"
pn = "pn"             # used as a normal name in debug-symbol-terrain.wgsl

# Usernames
Healthire = "Healthire"
REASY = "REASY"

[type.rust.extend-identifiers]
D3DCOLORtoUBYTE4 = "D3DCOLORtoUBYTE4"
