[package]
name = "wgpu-core-if-native-non-apple"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Workaround crate for enabling features in wgpu-core when targeting macOS/iOS"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]

[features]
gles = ["wgpu-core/gles"]
renderdoc = ["wgpu-core/renderdoc"]
vulkan = ["wgpu-core/vulkan"]

raw-window-handle = ["wgpu-core/raw-window-handle"]

[target.'cfg(any(windows, all(unix, not(target_arch = "wasm32"), not(target_vendor = "apple"))))'.dependencies]
wgpu-core.workspace = true
