name: validation-linux
on:
  pull_request:
    paths:
      - '.github/workflows/validation-linux.yml'
      - 'tests/out/spv/*.spvasm'
      - 'tests/out/glsl/*.glsl'
      - 'tests/out/dot/*.dot'
      - 'tests/out/wgsl/*.wgsl'
      - 'src/front/wgsl/*'
      - 'xtask/**'

jobs:
  validate-linux:
    name: SPIR-V + GLSL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get install spirv-tools glslang-tools graphviz

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            xtask -> target

      - run: cargo xtask validate spv

      - run: cargo xtask validate glsl

      - run: cargo xtask validate dot

      - run: cargo xtask validate wgsl
