[package]
name = "wgpu-precompile-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Macros for wgpu that enables precompiling shaders"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
proc-macro = true

[features]
msl = ["naga/msl-out"]
wgsl = ["naga/wgsl-out"]
spv = ["naga/spv-out"]
glsl = ["naga/glsl-out"]
hlsl = ["naga/hlsl-out"]
dxil = ["hlsl"]

[dependencies]
naga = { workspace = true, features = ["spv-in", "wgsl-in", "glsl-in"] }

quote.workspace = true
syn = { workspace = true, features = ["full"] }
hashbrown.workspace = true
