[package]
name = "wgpu-precompile-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Macros for wgpu that enables precompiling shaders"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
proc-macro = true

[features]

# Wgpu enables these features if the corresponding backend's feature is enabled.
# That means even if we are compiling to Windows, the MSL feature will be enabled
# by default. So eventually to not include unnecessary shader files we should add
# extra logic to detect target platforms and such.
metal = ["msl"]
webgpu = ["wgsl"]
vulkan = ["spirv"]
gles = ["glsl"]
dx12 = ["hlsl"]
angle = ["glsl"]
vulkan-portability = ["spirv"]
webgl = ["glsl"]

spirv = ["naga/spv-out"]
msl = ["naga/msl-out"]
wgsl = ["naga/wgsl-out"]
glsl = ["naga/glsl-out"]
hlsl = ["naga/hlsl-out"]

[dependencies]
naga = { workspace = true, features = ["spv-in", "wgsl-in", "glsl-in"] }

nanorand = { workspace = true, features = ["tls"] }
quote.workspace = true
syn = { workspace = true, features = ["full"] }
proc-macro2 = "1.0"
hashbrown.workspace = true
