name: CI

on:
  push:
  pull_request:

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  MSRV: 1.65

jobs:
  build:
    timeout-minutes: 5

    runs-on: windows-latest
    name: Build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust toolchain
        id: setup-rust
        run: |
          rustup toolchain install ${{ env.MSRV }} -c rustfmt,clippy --profile minimal

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          key: a # key for cache busting

      - name: format
        run: |
          cargo +${{ env.MSRV }} fmt --check

      - name: clippy
        run: |
          cargo +${{ env.MSRV }} clippy --all-features

      - name: doc
        run: |
          cargo +${{ env.MSRV }} doc --all-features --no-deps
