[package]
name = "wgpu-storage-texture-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu storage texture example"
publish = false

[[bin]]
name = "storage-texture"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
futures-intrusive.workspace = true
log.workspace = true
pollster.workspace = true
wgpu.workspace = true
wgpu-example.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
png.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "HtmlCanvasElement", "Document", "CanvasRenderingContext2d", "Window", "ImageData",
    "HtmlImageElement"
] }

[dev-dependencies]
wgpu-test.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true