[package]
name = "wgpu-core-if-arch-wasm32"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Workaround crate for enabling features in wgpu-core when targeting wasm32"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]

[features]
gles = ["wgpu-core/gles"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu-core.workspace = true
