blank_issues_enabled: false
contact_links:
  - name: Issues with shaders
    url: https://github.com/gfx-rs/naga/issues/new/choose
    about: Issues with or enhancements for the shader translation.
  - name: Question about wgpu
    url: https://github.com/gfx-rs/wgpu-rs/discussions/new
    about: Any questions about how to use wgpu should go here.
