[package]
name = "wgpu-hello-compute-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu hello compute example"
publish = false

[[bin]]
name = "hello-compute"
path = "src/main.rs"
harness = false

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
flume.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
wasm-bindgen-futures.workspace = true

[dev-dependencies]
wgpu-test.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true
