[package]
name = "wgpu-core-if-target-unix-non-apple"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Workaround crate for enabling in wgpu-core when targeting native non-apple native unix platforms"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]

[features]
gles = ["wgpu-core/gles"]
renderdoc = ["wgpu-core/renderdoc"]
vulkan = ["wgpu-core/vulkan"]

[target.'cfg(all(unix, not(target_os = "emscripten"), not(target_vendor = "apple")))'.dependencies]
wgpu-core.workspace = true
