[package]
name = "dummy"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]

[dependencies.wgc]
workspace = true
features = ["serial-pass", "trace"]
