[package]
name = "dummy"
version = "0.1.0"
authors = [
    "Dzmitry Malyshau <kvark@mozilla.com>",
]
edition = "2018"
publish = false

[features]

[dependencies.wgc]
path = "../wgpu-core"
package = "wgpu-core"
features = ["serial-pass", "trace"]
