[package]
name = "player"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "WebGPU trace player"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = false

[lib]
test = false

[[bin]]
name = "play"
test = false

[dependencies]
wgpu-types = { workspace = true, features = ["serde", "std"] }

bytemuck.workspace = true
env_logger.workspace = true
hashbrown.workspace = true
log.workspace = true
raw-window-handle.workspace = true
ron.workspace = true
winit = { workspace = true, optional = true }

[dev-dependencies]
serde.workspace = true

# Non-Webassembly
#
# We are a non-wasm only crate, and this allows us to compile.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.wgpu-core]
workspace = true
features = [
    "dx12",
    "gles",
    "metal",
    "replay",
    "strict_asserts",
    "vulkan",
    "wgsl",
]
