[package]
name = "wgpu-hello-triangle-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu hello triangle example"
publish = false

[[bin]]
name = "hello-triangle"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
