[package]
name = "wgpu-c-backend"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["wgsl"]
wgsl = ["wgpu/wgsl"]
spirv = ["wgpu/spirv"]

[dependencies]
ctor.workspace = true
log.workspace = true
wgpu = { workspace = true, features = ["custom"] }
wgpu-native = { package = "wgpu-native", git = "https://github.com/inner-daemons/wgpu-native", branch = "wgpu-native-complete" }

[target.'cfg(target_os = "macos")'.dependencies]
raw-window-metal = { workspace = true }

[lints]
workspace = true
