[package]
name = "wgpu-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Macros for wgpu"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
exclude = ["Cargo.lock"]
publish = false

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }
