[package]
name = "naga-test"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "common code for naga tests"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false


[features]
# Naga forwarded features
glsl-in = ["naga/glsl-in"]
glsl-out = ["naga/glsl-out"]
spv-in = ["naga/spv-in"]
spv-out = ["naga/spv-out"]
wgsl-in = ["naga/wgsl-in"]
wgsl-out = ["naga/wgsl-out"]
msl-out = ["naga/msl-out"]
dot-out = ["naga/dot-out"]
hlsl-out = ["naga/hlsl-out"]

[dependencies]
naga = { workspace = true, features = ["serialize", "deserialize"] }
spirv = { workspace = true, features = ["deserialize"] }
rspirv.workspace = true
ron.workspace = true
toml.workspace = true
bitflags.workspace = true
serde_json.workspace = true
serde.workspace = true
walkdir.workspace = true
env_logger.workspace = true
