[package]
name = "wgpu-stencil-triangle-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu stencil triangles example"
publish = false

[[bin]]
name = "stencil-triangles"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
wasm-bindgen-test.workspace = true
wgpu-example.workspace = true
wgpu.workspace = true
winit.workspace = true

[dev-dependencies]
wgpu-test.workspace = true
