[package]
name = "wgpu-texture-arrays-example"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "wgpu texture arrays example"
publish = false

[[bin]]
name = "texture-arrays"
path = "src/main.rs"
harness = false

[dependencies]
bytemuck.workspace = true
wgpu-example.workspace = true
wgpu.workspace = true
winit.workspace = true

[dev-dependencies]
wgpu-test.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true