[package]
name = "wgpu-core-if-target-windows"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Workaround crate for enabling wgpu-core when targeting windows"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]

[features]
dx12 = ["wgpu-core/dx12"]
gles = ["wgpu-core/gles"]
vulkan = ["wgpu-core/vulkan"]

[target.'cfg(windows)'.dependencies]
wgpu-core.workspace = true
