[package]
name = "wgpu-core-platform-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Feature unification helper crate for the WebAssembly platform"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
webgl = ["wgpu-hal/gles"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu-hal.workspace = true
