[package]
name = "wgpu-bug-repro-02-present-bugs"
edition = "2021"
rust-version = "1.87"
publish = false

[dependencies]
env_logger.workspace = true
log.workspace = true
pollster.workspace = true
raw-window-handle.workspace = true
wgpu.workspace = true
wgpu-core.workspace = true
wgpu-hal.workspace = true
wgpu-types.workspace = true
winit.workspace = true
