[package]
name = "wgpu-benchmark"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "wgpu benchmarking suite"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = false

[[bench]]
harness = false
name = "wgpu-benchmark"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
bincode = { workspace = true, features = ["serde"] }
bytemuck.workspace = true
naga = { workspace = true, features = [
    "deserialize",
    "glsl-in",
    "glsl-out",
    "hlsl-out",
    "msl-out",
    "serialize",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }
naga-test = { workspace = true, features = [] }
nanorand.workspace = true
pico-args.workspace = true
pollster.workspace = true
profiling.workspace = true
rayon.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
termcolor.workspace = true
tracy-client = { workspace = true, optional = true }
wgpu.workspace = true

[features]
tracy = ["dep:tracy-client"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("tracy"))',
] }
