name: changelog

on:
  pull_request:
    paths:
      - ".github/workflows/changelog.yml"
      - "CHANGELOG.md"
      - "xtask/**/*"
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  #
  # Dependency versioning
  #

  # This is the MSRV used by all repository infrastructure.
  REPO_MSRV: "1.93"

  #
  # Environment variables
  #

  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: "1"
  CACHE_SUFFIX: c # cache busting

jobs:
  changelog:
    timeout-minutes: 2

    name: Check changelog for errors
    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      # NOTE: Keep label name(s) in sync. with `xtask`'s implementation.
      - name: Run `cargo xtask changelog …`
        env:
          GITHUB_EVENT_PULL_REQUEST_BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          cargo xtask changelog "origin/${GITHUB_EVENT_PULL_REQUEST_BASE_REF}" ${{ contains(github.event.pull_request.labels.*.name, 'changelog: released entry changed') && '--allow-released-changes' || ''  }}
