name: changelog

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'
      - 'xtask/**/*'
    types:
      - opened
      - synchronize
      - reopened

env:
  #
  # Dependency versioning
  #

  # This is the MSRV used by `wgpu` itself and all surrounding infrastructure.
  REPO_MSRV: "1.88"

  #
  # Environment variables
  #

  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: '1'
  CACHE_SUFFIX: c # cache busting

jobs:
  changelog:
    timeout-minutes: 1

    name: Check changelog for errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run `cargo xtask changelog …`
        run: |
          cargo --quiet xtask changelog --emit-github-messages "origin/${{ github.event.pull_request.base.ref }}" 2> >(tee --append "$GITHUB_STEP_SUMMARY" >&2)
