name: validation-linux
on:
  pull_request:
    paths:
    - 'tests/out/spv/*.spvasm'
    - 'tests/out/glsl/*.glsl'
    - 'tests/out/dot/*.dot'
    - 'tests/out/wgsl/*.wgsl'
    - 'src/front/wgsl/*'

jobs:
  validate-linux:
    name: SPIR-V + GLSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: sudo apt-get install spirv-tools glslang-tools graphviz
      - run: make validate-spv
      - run: make validate-glsl
      - run: make validate-dot
      - run: make validate-wgsl
