name: xtask

on:
  pull_request:
    paths:
      - ".github/workflows/xtask.yml"
      - "xtask/**/*"

env:
  #
  # Dependency versioning
  #

  # This is the MSRV used by `wgpu` itself and all surrounding infrastructure.
  REPO_MSRV: "1.88"

  #
  # Environment variables
  #

  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: "1"
  CACHE_SUFFIX: c # cache busting

jobs:
  changelog:
    timeout-minutes: 2

    name: Run `cargo test` in `xtask/`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run `cargo test` in `xtask/`
        run: |
          cd xtask
          cargo test
